name: Build macOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyobjc psutil pyperclip
    
    - name: Build with PyInstaller
      run: |
        # 创建 spec 文件
        echo '# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ["safeclip.py"],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=["AppKit", "Quartz", "Foundation", "objc", "psutil", "PyObjCTools.AppHelper"],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="SafeClip",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="SafeClip",
)
app = BUNDLE(
    coll,
    name="SafeClip.app",
    icon=None,
    bundle_identifier="com.safeclip.app",
    info_plist={
        "NSPrincipalClass": "NSApplication",
        "NSAppleScriptEnabled": False,
        "LSUIElement": True,
        "CFBundleName": "SafeClip",
        "CFBundleDisplayName": "SafeClip",
        "CFBundleIdentifier": "com.safeclip.app",
        "CFBundleVersion": "1.0.0",
        "CFBundleShortVersionString": "1.0.0",
        "NSHumanReadableCopyright": "Copyright 2025 SafeClip. All rights reserved.",
    }
)' > SafeClip.spec
        
        # 构建应用
        pyinstaller SafeClip.spec
        
        # 压缩应用为 zip 文件以便下载
        cd dist && zip -r SafeClip-macOS.zip SafeClip.app
    
    - name: Upload macOS App
      uses: actions/upload-artifact@v3
      with:
        name: SafeClip-macOS
        path: dist/SafeClip-macOS.zip
