name: Build macOS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pyobjc psutil pyperclip
    
    - name: Build with PyInstaller
      run: |
        # 使用 PyInstaller 构建应用
        pyinstaller --windowed --onedir --name SafeClip safeclip.py --hidden-import AppKit --hidden-import Quartz --hidden-import Foundation --hidden-import objc --hidden-import psutil --hidden-import PyObjCTools.AppHelper
    
    - name: Create Info.plist
      run: |
        # 创建临时 Info.plist 文件
        echo '<?xml version="1.0" encoding="UTF-8"?>' > Info.plist
        echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> Info.plist
        echo '<plist version="1.0">' >> Info.plist
        echo '<dict>' >> Info.plist
        echo '    <key>CFBundleDevelopmentRegion</key>' >> Info.plist
        echo '    <string>English</string>' >> Info.plist
        echo '    <key>CFBundleDisplayName</key>' >> Info.plist
        echo '    <string>SafeClip</string>' >> Info.plist
        echo '    <key>CFBundleExecutable</key>' >> Info.plist
        echo '    <string>SafeClip</string>' >> Info.plist
        echo '    <key>CFBundleIconFile</key>' >> Info.plist
        echo '    <string>icon-windowed.icns</string>' >> Info.plist
        echo '    <key>CFBundleIdentifier</key>' >> Info.plist
        echo '    <string>com.safeclip.app</string>' >> Info.plist
        echo '    <key>CFBundleInfoDictionaryVersion</key>' >> Info.plist
        echo '    <string>6.0</string>' >> Info.plist
        echo '    <key>CFBundleName</key>' >> Info.plist
        echo '    <string>SafeClip</string>' >> Info.plist
        echo '    <key>CFBundlePackageType</key>' >> Info.plist
        echo '    <string>APPL</string>' >> Info.plist
        echo '    <key>CFBundleShortVersionString</key>' >> Info.plist
        echo '    <string>1.0.0</string>' >> Info.plist
        echo '    <key>CFBundleVersion</key>' >> Info.plist
        echo '    <string>1.0.0</string>' >> Info.plist
        echo '    <key>LSUIElement</key>' >> Info.plist
        echo '    <true/>' >> Info.plist
        echo '    <key>NSAppleScriptEnabled</key>' >> Info.plist
        echo '    <false/>' >> Info.plist
        echo '    <key>NSHumanReadableCopyright</key>' >> Info.plist
        echo '    <string>Copyright 2025 SafeClip. All rights reserved.</string>' >> Info.plist
        echo '    <key>NSPrincipalClass</key>' >> Info.plist
        echo '    <string>NSApplication</string>' >> Info.plist
        echo '</dict>' >> Info.plist
        echo '</plist>' >> Info.plist
        
        # 复制到应用包中
        cp Info.plist dist/SafeClip.app/Contents/Info.plist
    
    - name: Package App
      run: |
        # 压缩应用为 zip 文件以便下载
        cd dist && zip -r SafeClip-macOS.zip SafeClip.app
    
    - name: Upload macOS App
      uses: actions/upload-artifact@v3
      with:
        name: SafeClip-macOS
        path: dist/SafeClip-macOS.zip
